# SPDX-License-Identifier: GPL-2.0

spinand-objs := core.o gigadevice.o gsto.o macronix.o micron.o toshiba.o winbond.o foresee.o etron.o esmt.o fmsh.o dosilicon.o
obj-$(CONFIG_MTD_SPI_NAND) += spinand.o
